### ISSUE TITLE
Angular build error

### ISSUE THREAD

**Issue by saravananpsg** [galvinw/trumap#12]
@galvinw  Auth.session.service is not found while trying to build the latest version. Kindly advice how to proceed further.

ERROR in src/public/app/app.component.ts(3,29): error TS2307: Cannot find module './providers/auth/auth.session.service'.
src/public/app/app.module.ts(48,29): error TS2307: Cannot find module './providers/auth/auth.session.service'.

**Comment by galvinw** [comment]
seems to be npm run build is not being run
